version: '2'

services:
  db:
    # Note you cannot scale if you use container_name
    container_name: howamidoing-backend-db
    image: kartoza/postgis:12.0
    volumes:
      - ./backups:/backups
    environment:
      - USERNAME=docker
      - PASS=docker
    restart: unless-stopped
  web:
    # Note you cannot scale if you use container_name
    container_name: howamidoing-backend-web
    build: ./
    environment:
      - DEFAULT_DB_URL=postgis://docker:docker@db/gis
      - DJANGO_SETTINGS_MODULE=project.config.local
    volumes:
      - ./:/code
    command: bash -c "python manage.py runserver 0.0.0.0:8080"
    ports:
      - "51202:8080"
    links:
      - db:db
    restart: unless-stopped
    user: root