version: '2'

services:
  db:
    # Note you cannot scale if you use container_name
    container_name: howamidoing-backend-db
    image: kartoza/postgis:9.3-2.1
    volumes:
      - ./backups:/backups
    environment:
      - USERNAME=docker
      - PASS=docker
    restart: unless-stopped
  web:
    # Note you cannot scale if you use container_name
    container_name: howamidoing-backend-web
    build: ./
    environment:
      - DJANGO_SECRET_KEY=Local
      - DATABASE_NAME=gis
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - DATABASE_HOST=db
      - DEFAULT_DB_URL=postgis://docker:docker@db:5432/gis
      - DJANGO_SETTINGS_MODULE=project.config.local
    volumes:
      - ./:/code
#    command: bash -c "python manage.py migrate &&
#                      python manage.py collectstatic &&
#                      python manage.py runserver 0.0.0.0:8080"
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "51202:8080"
    links:
      - db:db
    restart: unless-stopped
    user: root